### PR TITLE
[opentdf-client] Better support for Conan 2.0

### PR DESCRIPTION
**Pull request by uilianries**
- Update dependencies versions
- The project requires C++17, not 14, as specified in the recipe
- jwt-cpp/0.6.0 seems be broken, let's keep 0.4.0
- check_min_cppstd will be replaced on Conan 1.51.0 (only the namespace)
- ms_gsl actually generates Microsoft.GSL cmake file
- Add set_property to support CMakeDeps generator
- Use positive options always to avoid prone logic
- Update test_package to use new cross_building import
- Keep only 3 latest releases, according to CCI policy
- Add patches to fix cmake install and find_package
- Add patch to fix missing fstream

Related PR https://github.com/conan-io/conan-center-index/pull/12024

### CODE REVIEW

**Comment by uilianries** [comment]
1.0.0 needs some patch

**Comment by patmantru** [comment]
That looks really great!  Thank you so much for taking the time to work on this!!!

**Review by patmantru — APPROVED** [review]
Looks good!  Thank you!

**Comment by patmantru** [comment]
Grr...  Still getting errors trying to use tools.Version, also still getting version skew errors:

ERROR: Conflict in libxml2/2.9.14:
    'libxml2/2.9.14' requires 'libiconv/1.17' while 'boost/1.79.0' requires 'libiconv/1.16'.
    To fix this conflict you need to override the package 'libiconv' in your root package.
    
Still working on it...

**Comment by uilianries** [comment]
@patmantru The PR https://github.com/conan-io/conan-center-index/pull/12024 will fix it

**Pull request merged**
